<a href="https://colab.research.google.com/github/Sumin0411/SKTFlyAI/blob/main/01_numpy_tutorial(12_19).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy Tutorial

In [ ]:
import numpy as np

In [ ]:
print(np.__version__)

1.23.5


### Numpy array

In [ ]:
arr = [1,2,3,4,5]
type(arr)

list

In [ ]:
# ndarray 객체
a = np.array(arr)
type(a)

numpy.ndarray

In [ ]:
# numpy array 속성
print(type(a))
print(a.dtype)
print(type(a.shape))

<class 'numpy.ndarray'>
int64
<class 'tuple'>


In [ ]:
a1 = np.array([1,2,3,4,5])
print(a1)

[1 2 3 4 5]


In [ ]:
a2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(a2)
print(a2.shape)
print(a2[0,0], a2[1,1], a2[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
1 5 9


In [ ]:
a3 = np.array([[[1,2,3], [4,5,6], [7,8,9]],[[1,2,3], [4,5,6], [7,8,9]], [[1,2,3], [4,5,6], [7,8,9]]])
print(a3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [ ]:
#shape (3,1,3)인 넘파이 배열
array = np.random.rand(3, 1, 3)
print(array)


[[[0.41509809 0.92672462 0.88071889]]

 [[0.88363805 0.17661806 0.79715384]]

 [[0.73241271 0.96575663 0.5404998 ]]]


### arange 함수

In [ ]:
arr = np.arange(12, 2, -1)
arr

array([12, 11, 10,  9,  8,  7,  6,  5,  4,  3])

In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.arange(12).shape
a= np.arange(12).reshape(3,4)

In [ ]:
b = np.zeros_like(a)
b

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 차원 변화

In [ ]:
a.reshape(3,4)
a.shape

(3, 4)

In [ ]:
a.reshape(3,2,2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [ ]:
a.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
a.reshape(3,4,-1) #_0, _1 등 앞에 숫자가 존재

array([[[ 0],
        [ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6],
        [ 7]],

       [[ 8],
        [ 9],
        [10],
        [11]]])

### 범용 함수
![](https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FcnGesf%2FbtqCgmUCssf%2FfkMlRnpeHRjVHYEoi2jwB1%2Fimg.png)

In [ ]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.sum(a, axis=0)

array([12, 15, 18, 21])

In [ ]:
np.sum(a, axis=1)

array([ 6, 22, 38])

In [ ]:
np.mean(a) # 평균 구하기

5.5

In [ ]:
np.mean(a, axis = 1)

array([1.5, 5.5, 9.5])

### argmax

In [ ]:
a = np.array([2,3,7,5,6])
np.argmax(a)

2

In [ ]:
a= np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])


### 인덱싱 : 차원이 줄어든다
### 슬라이싱 : 차원이 보존됨

In [ ]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
a[3]

3

In [ ]:
a[3:] #index[3]에서 끝까지

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
a[-5:]

array([ 7,  8,  9, 10, 11])

In [ ]:
a = np.arange(12).reshape(3,-1)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# a[1][1]
a[1,1]

5

In [ ]:
# a[1,2:]
a[0,2:]

array([2, 3])

In [ ]:
a[1:, 2:]

array([[ 6,  7],
       [10, 11]])

### Fancy indexing

In [ ]:
a[[2,0]]

array([[ 8,  9, 10, 11],
       [ 0,  1,  2,  3]])

### boolean indexing

In [ ]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [ ]:
idx = [True, False, True, False, False]
a[idx]

array([0, 2])

In [ ]:
a[a > 2]

array([3, 4])

### BroadCasting

In [ ]:
x = np.arange(6).reshape(3,2)
x

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
y = np.arange(6).reshape(2,3)
y

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
z = np.array([1,2,3])
z

array([1, 2, 3])

In [ ]:
y + z

array([[1, 3, 5],
       [4, 6, 8]])

### 배열 합치기
-stack(axis의 갯수가 증가함)

-concatenate(axis 유지)

In [ ]:
X = np.array([[1,1],[2,2]])
X

array([[1, 1],
       [2, 2]])

In [ ]:
Y = np.array([[3,3], [4,4]])
Y

array([[3, 3],
       [4, 4]])

In [ ]:
Z = np.stack((X, Y))
Z

array([[[1, 1],
        [2, 2]],

       [[3, 3],
        [4, 4]]])