<a href="https://colab.research.google.com/github/Sumin0411/SKTFlyAI/blob/main/04_SVM_bin_diabates(12_27).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# support vector machine - 이진분류
* 피마인디언 당뇨병 데이터 셋

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

1. 데이터 준비

In [ ]:
!wget https://raw.githubusercontent.com/devdio/datasets/main/diabetes.csv

--2023-12-27 03:05:40--  https://raw.githubusercontent.com/devdio/datasets/main/diabetes.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 23873 (23K) [text/plain]
Saving to: ‘diabetes.csv.10’

diabetes.csv.10     100%[===================>]  23.31K  --.-KB/s    in 0.003s  

2023-12-27 03:05:40 (8.66 MB/s) - ‘diabetes.csv.10’ saved [23873/23873]



In [ ]:
diabates = pd.read_csv('diabetes.csv')
diabates.shape

(768, 9)

In [ ]:
df = diabates.copy()
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [ ]:
df.info() #datatype 보기

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [ ]:
df.describe().T

count        mean         std     min       25%  \
Pregnancies               768.0    3.845052    3.369578   0.000   1.00000   
Glucose                   768.0  120.894531   31.972618   0.000  99.00000   
BloodPressure             768.0   69.105469   19.355807   0.000  62.00000   
SkinThickness             768.0   20.536458   15.952218   0.000   0.00000   
Insulin                   768.0   79.799479  115.244002   0.000   0.00000   
BMI                       768.0   31.992578    7.884160   0.000  27.30000   
DiabetesPedigreeFunction  768.0    0.471876    0.331329   0.078   0.24375   
Age                       768.0   33.240885   11.760232  21.000  24.00000   
Outcome                   768.0    0.348958    0.476951   0.000   0.00000   

                               50%        75%     max  
Pregnancies                 3.0000    6.00000   17.00  
Glucose                   117.0000  140.25000  199.00  
BloodPressure              72.0000   80.00000  122.00  
SkinThickness              23.0000   32.00000   99.00  
Insulin                    30.5000  127.25000  846.00  
BMI                        32.0000   36.60000   67.10  
DiabetesPedigreeFunction    0.3725    0.62625    2.42  
Age                        29.0000   41.00000   81.00  
Outcome                     0.0000    1.00000    1.00

In [ ]:
df['Outcome'].value_counts()

0    500
1    268
Name: Outcome, dtype: int64

### 2. 테스트 데이터 분리

In [ ]:
df.head() # 상위 5개 데이터 분리

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [ ]:
X = df.drop("Outcome", axis = 1)
X.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  
0                     0.627   50  
1                     0.351   31  
2                     0.672   32  
3                     0.167   21  
4                     2.288   33

In [ ]:
y = df['Outcome']
y.head()

0    1
1    0
2    1
3    0
4    1
Name: Outcome, dtype: int64

In [ ]:
# sklearn 함수
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 50, stratify = y)

In [ ]:
print(X_train.shape, X_test.shape)
print(y_train.shape, y_test.shape)

(614, 8) (154, 8)
(614,) (154,)


In [ ]:
y_train.value_counts()

0    400
1    214
Name: Outcome, dtype: int64

In [ ]:
y_test.value_counts()

0    100
1     54
Name: Outcome, dtype: int64

### 3. 데이터 전처리

결측치

In [ ]:
# df.isnull().sum()
X_train.isna().sum(axis=0)

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
dtype: int64

이상치

In [ ]:
X_train.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
377            1       87             60             37       75  37.2   
687            1      107             50             19        0  28.3   
613            6      105             80             28        0  32.5   
31             3      158             76             36      245  31.6   
557            8      110             76              0        0  27.8   

     DiabetesPedigreeFunction  Age  
377                     0.509   22  
687                     0.181   29  
613                     0.878   26  
31                      0.851   28  
557                     0.237   58


- 0인 값을 가진 sample(row)을 지우기

In [ ]:
df1 = X_train.copy()
df1.shape

(614, 8)

In [ ]:
df1.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age'],
      dtype='object')

In [ ]:
cols = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']

In [ ]:
df1 = df1[cols].replace(0, np.nan)
df1.isna().sum()

Glucose            3
BloodPressure     31
SkinThickness    188
Insulin          302
BMI                8
dtype: int64

In [ ]:
df1 = df.dropna()
df1.shape

(768, 9)

- 0인 값을 적당한 값으로 채워넣는 방법을 선택한다.

In [ ]:
df2 = X_train.copy()
df2.shape

(614, 8)

In [ ]:
df2[cols] = df2[cols].replace(0, np.nan)
df2.isna().sum()

Pregnancies                   0
Glucose                       3
BloodPressure                31
SkinThickness               188
Insulin                     302
BMI                           8
DiabetesPedigreeFunction      0
Age                           0
dtype: int64

In [ ]:
df2.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age'],
      dtype='object')

In [ ]:
df2['Glucose'] = df2['Glucose'].fillna(df2['Glucose'].median())

In [ ]:
df2['BloodPressure'] = df2['BloodPressure'].fillna(df2['BloodPressure'].median())

In [ ]:
df2['SkinThickness'] = df2['SkinThickness'].fillna(df2['SkinThickness'].median())

In [ ]:
df2['Insulin'] = df2['Insulin'].fillna(df2['Insulin'].median())

In [ ]:
df2['BMI'] = df2['BMI'].fillna(df2['BMI'].median())

In [ ]:
df2.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
dtype: int64

In [ ]:
df.describe().T

count        mean         std     min       25%  \
Pregnancies               768.0    3.845052    3.369578   0.000   1.00000   
Glucose                   768.0  120.894531   31.972618   0.000  99.00000   
BloodPressure             768.0   69.105469   19.355807   0.000  62.00000   
SkinThickness             768.0   20.536458   15.952218   0.000   0.00000   
Insulin                   768.0   79.799479  115.244002   0.000   0.00000   
BMI                       768.0   31.992578    7.884160   0.000  27.30000   
DiabetesPedigreeFunction  768.0    0.471876    0.331329   0.078   0.24375   
Age                       768.0   33.240885   11.760232  21.000  24.00000   
Outcome                   768.0    0.348958    0.476951   0.000   0.00000   

                               50%        75%     max  
Pregnancies                 3.0000    6.00000   17.00  
Glucose                   117.0000  140.25000  199.00  
BloodPressure              72.0000   80.00000  122.00  
SkinThickness              23.0000   32.00000   99.00  
Insulin                    30.5000  127.25000  846.00  
BMI                        32.0000   36.60000   67.10  
DiabetesPedigreeFunction    0.3725    0.62625    2.42  
Age                        29.0000   41.00000   81.00  
Outcome                     0.0000    1.00000    1.00

In [ ]:
medians = dict()
for c in df2.columns:
    medians[c] = df2[c].median()
    df2[c] = df2[c].fillna(df2[c].median())

print(medians)
df2.head()

{'Pregnancies': 3.0, 'Glucose': 118.0, 'BloodPressure': 72.0, 'SkinThickness': 29.0, 'Insulin': 127.5, 'BMI': 32.0, 'DiabetesPedigreeFunction': 0.3705, 'Age': 29.0}


Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
377            1     87.0           60.0           37.0     75.0  37.2   
687            1    107.0           50.0           19.0    127.5  28.3   
613            6    105.0           80.0           28.0    127.5  32.5   
31             3    158.0           76.0           36.0    245.0  31.6   
557            8    110.0           76.0           29.0    127.5  27.8   

     DiabetesPedigreeFunction  Age  
377                     0.509   22  
687                     0.181   29  
613                     0.878   26  
31                      0.851   28  
557                     0.237   58

스케일링

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_s = scaler.fit_transform(X_train)
X_train_s

array([[-0.84625065, -1.09979019, -0.44846255, ...,  0.66781515,
         0.09558476, -0.96454961],
       [-0.84625065, -0.45814141, -0.94792928, ..., -0.46619022,
        -0.86744524, -0.36839859],
       [ 0.63408524, -0.52230629,  0.5504709 , ...,  0.06895838,
         1.17899352, -0.62389188],
       ...,
       [ 0.33801806,  1.17806299,  0.05100418, ..., -0.27506572,
        -0.7911075 ,  2.5271921 ],
       [-0.84625065,  0.56849664, -1.14771597, ..., -0.41522368,
         0.52131449, -0.96454961],
       [-0.84625065, -0.49022385,  0.05100418, ...,  0.28556615,
        -0.98195186, -0.96454961]])

In [ ]:
scaler.mean_

array([  3.85830619, 121.28013029,  68.97882736,  20.36644951,
        80.47557003,  31.95879479,   0.47644463,  33.3257329 ])

In [ ]:
scaler.var_

array([1.14082616e+01, 9.71550192e+02, 4.00854601e+02, 2.61714249e+02,
       1.39317706e+04, 6.15956148e+01, 1.16002687e-01, 1.37874354e+02])

In [ ]:
y_train = y_train.values
type(y_train)

numpy.ndarray

### 4. 학습
- SVC

In [ ]:
from sklearn.svm import SVC

clf = SVC(random_state=50)
clf.fit(X_train_s, y_train)

SVC(random_state=50)

### 5. 예측

테스트 데이터 전처리 먼저
- 0인 값을 위에서 계산한 값으로 넣는 작업
- scaling

In [ ]:
df3 = X_test.copy()

df3[cols] = df3[cols].replace(0,np.nan)
for d in df3.columns:
  medians[d] = df3[d].median()
  df3[d] = df3[d].fillna(df3[d].median())

X_test = df3.copy()

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_test_s = scaler.fit_transform(X_test)

from sklearn.metrics import accuracy_score

y_pred = clf.predict(X_test_s)
acc = accuracy_score(y_test, y_pred)
acc

0.7272727272727273

### 6. 튜닝
C, gamma, kernel, degrees, hyper parameter tuning

In [ ]:
from sklearn.model_selection import GridSearchCV

params = {
    "C" : [0.1, 1, 10],
    "gamma" : [0.01, 0.1],
    "degree" : [2,3],
    "kernel" : ["poly", "rbf"]
}


grid_cv = GridSearchCV(SVC(), params, cv = 5, refit = True, verbose = 3)
grid_cv.fit(X_train_s, y_train)

Fitting 5 folds for each of 24 candidates, totalling 120 fits
[CV 1/5] END C=0.1, degree=2, gamma=0.01, kernel=poly;, score=0.650 total time=   0.0s
[CV 2/5] END C=0.1, degree=2, gamma=0.01, kernel=poly;, score=0.650 total time=   0.0s
[CV 3/5] END C=0.1, degree=2, gamma=0.01, kernel=poly;, score=0.650 total time=   0.0s
[CV 4/5] END C=0.1, degree=2, gamma=0.01, kernel=poly;, score=0.650 total time=   0.0s
[CV 5/5] END C=0.1, degree=2, gamma=0.01, kernel=poly;, score=0.656 total time=   0.0s
[CV 1/5] END C=0.1, degree=2, gamma=0.01, kernel=rbf;, score=0.650 total time=   0.1s
[CV 2/5] END C=0.1, degree=2, gamma=0.01, kernel=rbf;, score=0.650 total time=   0.1s
[CV 3/5] END C=0.1, degree=2, gamma=0.01, kernel=rbf;, score=0.650 total time=   0.1s
[CV 4/5] END C=0.1, degree=2, gamma=0.01, kernel=rbf;, score=0.650 total time=   0.0s
[CV 5/5] END C=0.1, degree=2, gamma=0.01, kernel=rbf;, score=0.656 total time=   0.0s
[CV 1/5] END C=0.1, degree=2, gamma=0.1, kernel=poly;, score=0.642 total 

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [0.1, 1, 10], 'degree': [2, 3],
                         'gamma': [0.01, 0.1], 'kernel': ['poly', 'rbf']},
             verbose=3)

In [ ]:
grid_cv.best_estimator_

SVC(C=1, degree=2, gamma=0.01)

In [ ]:
grid_cv.best_score_

0.7801679328268692

In [ ]:
grid_cv.best_params_

{'C': 1, 'degree': 2, 'gamma': 0.01, 'kernel': 'rbf'}

### 베스트 모델 학습

In [ ]:
clf = SVC(C = 1, degree = 2, gamma = 0.01, kernel = 'rbf')
clf.fit(X_train_s, y_train)

SVC(C=1, degree=2, gamma=0.01)

### 7. 모델 저장

In [ ]:
import pickle #pickle : 일반 텍스트를 파일로 저장할 때는 파일 입출력을 이용한다

with open('svc_c_1_degree_2_gamma_001_rbf.pickel', 'wb') as f:
  pickle.dump(clf, f)

In [ ]:
with open('standard_scaler.pickel', 'wb') as f:
  pickle.dump(scaler, f)

* 저장된 모델을 사용하기

In [ ]:
with open('svc_c_1_degree_2_gamma_001_rbf.pickel', 'rb') as f: #rb = road, wb = write
  clf = pickle.load(f)

clf

SVC(C=1, degree=2, gamma=0.01)

In [ ]:
with open('standard_scaler.pickel', 'rb') as f:
  scaler = pickle.load(f)

scaler

StandardScaler()

In [ ]:
scaler.mean_

array([  3.79220779, 120.83116883,  71.50649351,  28.55844156,
       134.37662338,  32.76623377,   0.45366234,  32.9025974 ])

### KNN 알고리즘 학습시키기
X_train_s, y_train
X_test_s, y_test

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

accuracy = []
for k in range(3, 50):
    clf_k = KNeighborsClassifier(n_neighbors = k)
    clf_k.fit(X_train_s, y_train)
    y_pred = clf_k.predict(X_test_s)
    acc = accuracy_score(y_test, y_pred)
    accuracy.append(acc)

max(accuracy), accuracy.index(max(accuracy))

(0.7662337662337663, 35)